# Generated by Django 5.2.17 on 2026-10-03 22:18

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_full_name', models.CharField(blank=True, max_length=100)),
                ('default_phone_number', models.CharField(blank=True, max_length=30)),
                ('default_street_address', models.CharField(blank=True, max_length=200)),
                ('default_postcode', models.CharField(blank=True, max_length=20)),
                ('default_town_or_city', models.CharField(blank=True, max_length=100)),
                ('default_country', django_countries.fields.CountryField(blank=True, default='CH', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
