# Generated by Django 5.2.18 on 2026-10-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(default='de', max_length=10),
        ),
    ]
