# Generated by Django 5.2.18 on 2026-10-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_personalization_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='weight_grams',
        ),
    ]
