# Generated by Django 5.2.18 on 2026-10-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productvariant_weight_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
