# Generated by Django 5.2.18 on 2026-10-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='personalization_required',
            field=models.BooleanField(default=False),
        ),
    ]
